name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux
    env:
      abi: armeabi-v7a,arm64-v8a,x86,x86_64
      ndk_version: 25.0.8775105
      cmake_version: 3.22.1
      platform: 23

    steps:
      - name: Install build dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm base-devel ghc git unzip haskell-shake libime opencc jdk11-openjdk python

      - name: Fetch source code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install NDK
        run: sdkmanager --install "ndk;${{ env.ndk_version }}"

      - name: Install cmake
        run: sdkmanager --install "cmake;${{ env.cmake_version }}"

      - name: Build
        run: |
          export ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk/${{ env.ndk_version }}
          export CMAKE_VERSION=${{ env.cmake_version }}
          export ANDROID_PLATFORM=${{ env.platform }}
          export ABI=${{ env.abi }}
          mkdir build
          cd build
          runghc ../Main.hs -j everything

      - name: Move libraries to prebuilt and compress
        run: |
          mkdir -p build/prebuilt
          cp -a build/{'spell-dict','chinese-addons-data','libime','fmt','libevent','libintl-lite','lua','opencc','boost'} \
                build/prebuilt/
          cd build
          tar --zstd -cf prebuilt.tar.zst prebuilt/

      - name: Upload prebuilt
        uses: actions/upload-artifact@v3
        with:
          path: build/prebuilt.tar.zst
